spring:
  application:
    name: api-gateway-keycloak
---
spring:
  profiles: cloud
  ssl:
    key-store: classpath:keystore.jks
    key-store-password: password
    key-password: password

ribbon:
  TrustStore: keystore.jks
  TrustStorePassword : password
  ReadTimeout: 60000
  IsSecure: true
  MaxAutoRetries: 1

zuul:
  ignored-services: '*'
  routes:
    foo-service:
      path: /api/**
      service-id: foo-service
      strip-prefix: false
security:
  basic:
    enabled: false
management:
  security:
    enabled: false
hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: false
        isolation:
          thread:
            timeoutInMilliseconds: 300000
---