spring:
  application:
    name: foo-service
---
spring:
  profiles: cloud
eureka:
  instance:
    secure-port-enabled: true
security:
  basic:
    enabled: false
management:
  security:
    enabled: false
---