---
spring:
  profiles: cloud
server:
  ssl:
    enabled: true
    key-alias: ${spring.application.name}
    key-store: classpath:${spring.application.name}.p12
    key-store-type: PKCS12
    key-store-password: password
  port: 8443
security:
  require-ssl: true
  basic:
    enabled: false
eureka:
  instance:
    secure-port-enabled: true
    prefer-ip-address: true
management:
  security:
    enabled: false
https:
  enforcer:
    enabled: true
---