spring:
  application:
    name: zuul-api-gateway-keycloak
---
spring:
  profiles: cloud
# ===================================================================
# To enable SSL, generate a certificate using:
# keytool -genkey -alias service1 -storetype PKCS12 -keyalg RSA -keysize 2048 -keystore keystore.p12 -validity 3650
#
# You can also use Let's Encrypt:
# https://maximilian-boehm.com/hp2121/Create-a-Java-Keystore-JKS-from-Let-s-Encrypt-Certificates.htm
#
# Then, modify the server.ssl properties so your "server" configuration looks like:
#
# server:
#    port: 8443
#    ssl:
#        key-store: keystore.p12
#        key-store-password: <your-password>
#        keyStoreType: PKCS12
#        keyAlias: service1
# ===================================================================
#server:
#  ssl:
#    key-store: classpath:keystore.jks
#    key-store-password: password
#    key-password: password
#    key-alias: ${spring.application.name}
#    key-store-type: PKCS12
#
#ribbon:
#  TrustStore: keystore.jks
#  TrustStorePassword : password
#  ReadTimeout: 60000
#  IsSecure: true
#  MaxAutoRetries: 1
zuul:
  ignored-services: '*'
  prefix: ''
  routes:
    foo-service:
      path: /foo/**
      service-id: foo-service
      strip-prefix: false
  strip-prefix: false
security:
  basic:
    enabled: false
management:
  security:
    enabled: false
---