spring:
  application:
    name: zuul-api-gateway-keycloak
---
spring:
  profiles: cloud

ribbon:
  IsSecure: true

zuul:
  ignored-services: '*'
  prefix: ''
  routes:
    foo-service:
      path: /foo/**
      service-id: foo-service
      strip-prefix: false
  strip-prefix: false
security:
  basic:
    enabled: false
management:
  security:
    enabled: false
---