---
spring:
  profiles: cloud
server:
  ssl:
    key-store: classpath:${spring.application.name}.jks
    key-password: password
    key-alias: ${spring.application.name}
    key-store-type: PKCS12
zuul:
  ignored-services: '*'
  prefix: ''
  routes:
    foo-service:
      path: /foo/**
      service-id: foo-service
      strip-prefix: false
  strip-prefix: false
security:
  basic:
    enabled: false
management:
  security:
    enabled: false
eureka:
  instance:
    secure-port-enabled: true
---