---
spring:
  profiles: cloud
server:
  ssl:
    enabled: true
    key-alias: ${spring.application.name}
    key-store: classpath:${spring.application.name}.p12
    key-store-type: PKCS12
    key-store-password: password
    key-password: password
security:
  basic:
    enabled: false
zuul:
  ignored-services: '*'
  prefix: ''
  routes:
    foo-service:
      path: /foo/**
      service-id: foo-service
      strip-prefix: false
    uaa-keycloak:
      path: /auth/**
      service-id: uaa-keycloak
      strip-prefix: false
  strip-prefix: false
management:
  security:
    enabled: false
eureka:
  instance:
    secure-port-enabled: true
---